# Site
name: 'Learn With Souren'
description: 'Step-by-step guides on various topics, from basic programming to advanced concepts.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'LearnWithPython'
email: 'souren94@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    Souren:
      name:           Souren
      site:           https://www.linkedin.com/in/souren/
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I'm Souren! I'm passionate about technology, especially in the realms of Python programming, deep learning, and image processing. With a background in computer science and a deep curiosity for how things work, I've spent years diving into the intricacies of these fields."
      email:          souren94@gmail.com
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Souren
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]